# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 8 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : ./

title : Futranbg

author:
  name: Phuong Tran
  role: Tekcafe technical team leader
  email: phuongtran@tekcafe.vn
  github: futranbg
  facebook: phuongtranbg
  googleplus: +phuongtran86
  bio: "WE MAKE THE DIFFERENT"
  Futranbg: https://raw.githubusercontent.com/futranbg/futranbg.github.io/master/logo-team.png
