# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: kramdown

highlighter: pygments
paginate: 8 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

BASE_PATH : http://blog.ankanbiswas.in/uno-dbyll

title : Futranbg

author:
  name: Phương Trần
  role: Tekcafe technical team leader
  email: phuongtran@tekcafe.vn
  github: futranbg
  facebook: phuongtranbg
  googleplus: +AnkanBiswasWorkspace
  bio: "Simple, clean, responsive and stylist theme for jekyll. "
  Tekcafe team: https://raw.githubusercontent.com/futranbg/futranbg.github.io/master/logo-team.png
